apiVersion: v1
kind: ResourceQuota
metadata:
  name: comfyui-quota
  namespace: comfyui
spec:
  hard:
    requests.cpu: "64"
    requests.memory: 256Gi
    requests.nvidia.com/gpu: "16"
    limits.cpu: "128"
    limits.memory: 512Gi
    limits.nvidia.com/gpu: "16"
    persistentvolumeclaims: "10"
    requests.storage: 2Ti
    pods: "5"
    services: "10"
    count/deployments.apps: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: comfyui-limits
  namespace: comfyui
spec:
  limits:
  - default:
      cpu: "32"
      memory: "128Gi"
      nvidia.com/gpu: "8"
    defaultRequest:
      cpu: "16"
      memory: "64Gi"
      nvidia.com/gpu: "8"
    type: Container
  - max:
      cpu: "64"
      memory: "256Gi"
      nvidia.com/gpu: "8"
    min:
      cpu: "1"
      memory: "1Gi"
      nvidia.com/gpu: "1"
    type: Container
